# Form implementation generated from reading ui file '/Users/dovi/ProductManagement/Final/management/ui/ProductMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 831)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetProductManagement = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetProductManagement.setGeometry(QtCore.QRect(10, 60, 441, 411))
        self.tableWidgetProductManagement.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tableWidgetProductManagement.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 10px;\n"
"    border: 2px solid #795d4c;\n"
"    background-color: #f5f5f5;\n"
"    font: 15pt \"Georgia\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #d1c4b2;\n"
"    padding: 5px;\n"
"    border: 1px solid #795d4c;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tableWidgetProductManagement.setObjectName("tableWidgetProductManagement")
        self.tableWidgetProductManagement.setColumnCount(4)
        self.tableWidgetProductManagement.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetProductManagement.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProductManagement.setItem(2, 3, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1131, 51))
        self.label.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Để nội dung không bị sát mép */\n"
"    background-color: rgb(52, 21, 21);\n"
"font: italic 25pt \"Garamond\";\n"
"color:rgb(250, 235, 215)\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidgetCustomerManagement = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetCustomerManagement.setGeometry(QtCore.QRect(470, 279, 421, 191))
        self.tableWidgetCustomerManagement.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableWidgetCustomerManagement.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 10px;\n"
"    border: 2px solid #795d4c;\n"
"    background-color: #f5f5f5;\n"
"    font: 15pt \"Georgia\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #d1c4b2;\n"
"    padding: 5px;\n"
"    border: 1px solid #795d4c;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tableWidgetCustomerManagement.setObjectName("tableWidgetCustomerManagement")
        self.tableWidgetCustomerManagement.setColumnCount(4)
        self.tableWidgetCustomerManagement.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomerManagement.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomerManagement.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomerManagement.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomerManagement.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomerManagement.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetCustomerManagement.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetCustomerManagement.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidgetCustomerManagement.setHorizontalHeaderItem(3, item)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(480, 480, 421, 281))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    font: 20pt \"Franklin Gothic Medium Cond\";\n"
"    color: rgb(77, 10, 24);\n"
"    border: 2px solid grey;  /* Viền màu xám */\n"
"    border-radius: 15px;  /* Bo góc 10px */\n"
"    padding: 10px;\n"
"    background-color: rgb(172, 164, 148);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;  /* Canh tiêu đề ở giữa */\n"
"    padding: 5px;\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 5px;  /* Bo góc cho phần tiêu đề */\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEditCustomerName = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditCustomerName.setGeometry(QtCore.QRect(200, 80, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditCustomerName.setFont(font)
        self.lineEditCustomerName.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditCustomerName.setObjectName("lineEditCustomerName")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(30, 150, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia,serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEditCustomerPhone = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditCustomerPhone.setGeometry(QtCore.QRect(200, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditCustomerPhone.setFont(font)
        self.lineEditCustomerPhone.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditCustomerPhone.setObjectName("lineEditCustomerPhone")
        self.pushButtonSaveCustomer = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonSaveCustomer.setGeometry(QtCore.QRect(20, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSaveCustomer.setFont(font)
        self.pushButtonSaveCustomer.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonSaveCustomer.setObjectName("pushButtonSaveCustomer")
        self.pushButtonClearCustomer = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonClearCustomer.setGeometry(QtCore.QRect(120, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClearCustomer.setFont(font)
        self.pushButtonClearCustomer.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonClearCustomer.setObjectName("pushButtonClearCustomer")
        self.pushButtonRemoveCustomer = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonRemoveCustomer.setGeometry(QtCore.QRect(320, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRemoveCustomer.setFont(font)
        self.pushButtonRemoveCustomer.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonRemoveCustomer.setObjectName("pushButtonRemoveCustomer")
        self.pushButtonSearchCustomer = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonSearchCustomer.setGeometry(QtCore.QRect(220, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearchCustomer.setFont(font)
        self.pushButtonSearchCustomer.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonSearchCustomer.setObjectName("pushButtonSearchCustomer")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 181, 31))
        self.label_7.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(30, 120, 181, 31))
        self.label_8.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_8.setObjectName("label_8")
        self.checkBoxNormal = QtWidgets.QCheckBox(parent=self.groupBox_3)
        self.checkBoxNormal.setGeometry(QtCore.QRect(140, 170, 87, 20))
        self.checkBoxNormal.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.checkBoxNormal.setObjectName("checkBoxNormal")
        self.checkBoxVIP = QtWidgets.QCheckBox(parent=self.groupBox_3)
        self.checkBoxVIP.setGeometry(QtCore.QRect(250, 170, 87, 20))
        self.checkBoxVIP.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.checkBoxVIP.setObjectName("checkBoxVIP")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(30, 40, 151, 31))
        self.label_10.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_10.setObjectName("label_10")
        self.lineEditCustomerId = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditCustomerId.setGeometry(QtCore.QRect(200, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditCustomerId.setFont(font)
        self.lineEditCustomerId.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditCustomerId.setObjectName("lineEditCustomerId")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 400, 211, 151))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    font: 15pt \"Franklin Gothic Medium Cond\";\n"
"    color: rgb(77, 10, 24);\n"
"    border: 2px solid grey;  /* Viền màu xám */\n"
"    border-radius: 15px;  /* Bo góc 10px */\n"
"    padding: 10px;\n"
"    background-color: rgb(172, 164, 148);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;  /* Canh tiêu đề ở giữa */\n"
"    padding: 5px;\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 5px;  /* Bo góc cho phần tiêu đề */\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonLineChart = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonLineChart.setGeometry(QtCore.QRect(50, 50, 121, 61))
        self.pushButtonLineChart.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Để chữ không bị sát mép */\n"
"font: 15pt \"Franklin Gothic Medium Cond\";\n"
"color: rgb(250, 235, 215);\n"
"background-color: rgb(52, 21, 21);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/management/ui/../../images/bar chart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLineChart.setIcon(icon)
        self.pushButtonLineChart.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonLineChart.setObjectName("pushButtonLineChart")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(910, 230, 211, 151))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    font: 15pt \"Franklin Gothic Medium Cond\";\n"
"    color: rgb(77, 10, 24);\n"
"    border: 2px solid grey;  /* Viền màu xám */\n"
"    border-radius: 15px;  /* Bo góc 10px */\n"
"    padding: 10px;\n"
"    background-color: rgb(172, 164, 148);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;  /* Canh tiêu đề ở giữa */\n"
"    padding: 5px;\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 5px;  /* Bo góc cho phần tiêu đề */\n"
"}\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButtonPieChart = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButtonPieChart.setGeometry(QtCore.QRect(50, 40, 121, 61))
        self.pushButtonPieChart.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Để chữ không bị sát mép */\n"
"font: 15pt \"Franklin Gothic Medium Cond\";\n"
"color: rgb(250, 235, 215);\n"
"background-color: rgb(52, 21, 21);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/management/ui/../../images/pie.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPieChart.setIcon(icon1)
        self.pushButtonPieChart.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonPieChart.setObjectName("pushButtonPieChart")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 480, 441, 281))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font: 20pt \"Franklin Gothic Medium Cond\";\n"
"    color: rgb(77, 10, 24);\n"
"    border: 2px solid grey;  /* Viền màu xám */\n"
"    border-radius: 15px;  /* Bo góc 10px */\n"
"    padding: 10px;\n"
"    background-color: rgb(172, 164, 148);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;  /* Canh tiêu đề ở giữa */\n"
"    padding: 5px;\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 5px;  /* Bo góc cho phần tiêu đề */\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia,serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEditProductId = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditProductId.setGeometry(QtCore.QRect(180, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditProductId.setFont(font)
        self.lineEditProductId.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditProductId.setObjectName("lineEditProductId")
        self.lineEditProductName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditProductName.setGeometry(QtCore.QRect(180, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditProductName.setFont(font)
        self.lineEditProductName.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditProductName.setObjectName("lineEditProductName")
        self.lineEditPrice = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPrice.setGeometry(QtCore.QRect(180, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPrice.setFont(font)
        self.lineEditPrice.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditQuantity.setGeometry(QtCore.QRect(180, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditQuantity.setFont(font)
        self.lineEditQuantity.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px; /* Bo góc 10px */\n"
"    border: 2px solid #795d4c; /* Viền */\n"
"    background-color: #f5f5f5; /* Màu nền */\n"
"    padding: 5px; /* Giúp chữ không bị sát mép */\n"
"}\n"
"")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSave.setGeometry(QtCore.QRect(20, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonClear.setGeometry(QtCore.QRect(120, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonRemove.setGeometry(QtCore.QRect(340, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRemove.setFont(font)
        self.pushButtonRemove.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonSave_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSave_2.setGeometry(QtCore.QRect(230, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSave_2.setFont(font)
        self.pushButtonSave_2.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.pushButtonSave_2.setObjectName("pushButtonSave_2")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia,serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia,serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(0, 150, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia,serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(" font-family: \"Georgia\", serif; \n"
"font: 18pt ")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(910, 60, 211, 151))
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    font: 15pt \"Franklin Gothic Medium Cond\";\n"
"    color: rgb(77, 10, 24);\n"
"    border: 2px solid grey;  /* Viền màu xám */\n"
"    border-radius: 15px;  /* Bo góc 10px */\n"
"    padding: 10px;\n"
"    background-color: rgb(172, 164, 148);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;  /* Canh tiêu đề ở giữa */\n"
"    padding: 5px;\n"
"    background-color: rgb(172, 164, 148);\n"
"    border-radius: 5px;  /* Bo góc cho phần tiêu đề */\n"
"}\n"
"")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButtonBarChart = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButtonBarChart.setGeometry(QtCore.QRect(50, 40, 121, 61))
        self.pushButtonBarChart.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; \n"
"    border: 2px solid #795d4c; \n"
"    background-color: #f5f5f5; \n"
"    padding: 5px; \n"
"font: 15pt \"Franklin Gothic Medium Cond\";\n"
"color: rgb(250, 235, 215);\n"
"background-color: rgb(52, 21, 21);\n"
"}")
        self.pushButtonBarChart.setIcon(icon)
        self.pushButtonBarChart.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBarChart.setObjectName("pushButtonBarChart")
        self.textBrowser_clock = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_clock.setGeometry(QtCore.QRect(470, 60, 421, 94))
        self.textBrowser_clock.setStyleSheet("#textBrowser_clock {\n"
"    background-color: rgb(172, 164, 148);  /* Màu nền nâu nhạt */\n"
"    color: #5C4033;             /* Màu chữ nâu đậm */\n"
"    font-size: 42px;            /* Kích thước chữ lớn */\n"
"    font-weight: bold;\n"
"    font-family: \'DS-Digital\', sans-serif; /* Font số điện tử */\n"
" \n"
"    border-radius: 10px;         /* Bo góc */\n"
"    padding: 15px;\n"
"    border: 2px solid #8B5A2B;  /* Viền nâu đậm */\n"
"\n"
"    /* Đảm bảo kích thước không bị bó hẹp */\n"
"    min-height: 60px; \n"
"    min-width: 200px; \n"
"}\n"
"")
        self.textBrowser_clock.setObjectName("textBrowser_clock")
        self.textBrowser_date = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_date.setGeometry(QtCore.QRect(470, 170, 421, 94))
        self.textBrowser_date.setStyleSheet("#textBrowser_date {\n"
"    background-color: rgb(172, 164, 148);  /* Màu nền nâu nhạt */\n"
"    color: #5C4033;             /* Màu chữ nâu đậm */\n"
"    font-size: 42px;            /* Kích thước chữ lớn */\n"
"    font-weight: bold;\n"
"    font-family: \'DS-Digital\', sans-serif; /* Font số điện tử */\n"
"\n"
"    border-radius: 10px;         /* Bo góc */\n"
"    padding: 15px;\n"
"    border: 2px solid #8B5A2B;  /* Viền nâu đậm */\n"
"\n"
"    /* Đảm bảo kích thước không bị bó hẹp */\n"
"    min-height: 60px; \n"
"    min-width: 200px; \n"
"}\n"
"")
        self.textBrowser_date.setObjectName("textBrowser_date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidgetProductManagement.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidgetProductManagement.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidgetProductManagement.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.tableWidgetProductManagement.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Unit Price"))
        item = self.tableWidgetProductManagement.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        __sortingEnabled = self.tableWidgetProductManagement.isSortingEnabled()
        self.tableWidgetProductManagement.setSortingEnabled(False)
        self.tableWidgetProductManagement.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Product Management"))
        item = self.tableWidgetCustomerManagement.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetCustomerManagement.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetCustomerManagement.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetCustomerManagement.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetCustomerManagement.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Customer Id"))
        item = self.tableWidgetCustomerManagement.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.tableWidgetCustomerManagement.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.tableWidgetCustomerManagement.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Customer Detail"))
        self.label_9.setText(_translate("MainWindow", "Type:"))
        self.pushButtonSaveCustomer.setText(_translate("MainWindow", "Save"))
        self.pushButtonClearCustomer.setText(_translate("MainWindow", "Clear"))
        self.pushButtonRemoveCustomer.setText(_translate("MainWindow", "Remove"))
        self.pushButtonSearchCustomer.setText(_translate("MainWindow", "Search"))
        self.label_7.setText(_translate("MainWindow", "Customer Name: "))
        self.label_8.setText(_translate("MainWindow", "Phone Number:"))
        self.checkBoxNormal.setText(_translate("MainWindow", "Normal"))
        self.checkBoxVIP.setText(_translate("MainWindow", "VIP"))
        self.label_10.setText(_translate("MainWindow", "Customer ID: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Revenue"))
        self.pushButtonLineChart.setText(_translate("MainWindow", "Line Chart"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Customer Type Distribution"))
        self.pushButtonPieChart.setText(_translate("MainWindow", "Pie Chart"))
        self.groupBox.setTitle(_translate("MainWindow", "Product Detail:"))
        self.label_2.setText(_translate("MainWindow", "Product Id:"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.pushButtonSave_2.setText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "Product Name:"))
        self.label_11.setText(_translate("MainWindow", "Price:"))
        self.label_12.setText(_translate("MainWindow", "Quantity:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Product Quantity"))
        self.pushButtonBarChart.setText(_translate("MainWindow", "Bar Chart"))
