# Form implementation generated from reading ui file '/Users/dovi/ProductManagement/Final/ui/MainWindowLogin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 680)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 421, 631))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/bf.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 40, 361, 291))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgba(250, 250, 230, 80); /* Beige siêu nhạt, trong suốt */\n"
"    border-radius: 10px; /* Bo góc mềm mại */\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(170, 110, 221, 41))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid ; \n"
"    background-color: rgba(240, 240, 240, 200); /* Màu nền xám nhạt, hơi trong suốt */\n"
"    border: 1px solid #d0d0d0; /* Viền mỏng màu xám nhạt */\n"
" font-family: \"Georgia\", serif; font: 18;\n"
"\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditUserPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserPassword.setGeometry(QtCore.QRect(170, 160, 221, 41))
        self.lineEditUserPassword.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid ; \n"
"    background-color: rgba(240, 240, 240, 200); /* Màu nền xám nhạt, hơi trong suốt */\n"
"    border: 1px solid #d0d0d0; /* Viền mỏng màu xám nhạt */\n"
" font-family: \"Georgia\", serif; font: 18;\n"
"\n"
"}\n"
"")
        self.lineEditUserPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditUserPassword.setObjectName("lineEditUserPassword")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 160, 111, 41))
        self.label_7.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
" font-family: \"Georgia\", serif; \n"
"font: 18pt \n"
"}")
        self.label_7.setObjectName("label_7")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(230, 230, 121, 41))
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    font: 18pt;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #d2b48c; /* Màu be nhạt */\n"
"    background-color: #f5f5dc; /* Màu be nhạt */\n"
"    color: black;\n"
"    padding: 5px 10px;\n"
" font-family: \"Georgia\", serif; \n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e0d5b7; /* Màu be hơi đậm khi hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #c8b693; /* Màu be sậm hơn khi nhấn */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/4115235_exit_logout_sign out_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon)
        self.pushButtonExit.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(90, 230, 121, 41))
        self.pushButtonLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    font: 18pt;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #d2b48c; \n"
"    background-color: #f5f5dc; \n"
"    color: black;\n"
"    padding: 5px 10px;\n"
" font-family: \"Georgia\", serif; \n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e0d5b7; \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #c8b693; \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/3535187_bottle_cafe_coffee_cup_drink_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon1)
        self.pushButtonLogin.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 111, 31))
        self.label_2.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
" font-family: \"Georgia\", serif; \n"
"font: 18pt \n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 281, 31))
        self.label_3.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
" font-family: \"Georgia\", serif; \n"
"font: 32pt \n"
"}")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Password: "))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "User\'s Name:"))
        self.label_3.setText(_translate("MainWindow", "MY COFFEE SHOP"))
