# Form implementation generated from reading ui file '/Users/dovi/ProductManagement/Final/ui/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1344, 847)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.headerWidget.setGeometry(QtCore.QRect(0, 0, 1331, 40))
        self.headerWidget.setStyleSheet("color: white;  \n"
"font-size: 14px;\n"
"background-color:  #8B5E5A;\n"
"")
        self.headerWidget.setObjectName("headerWidget")
        self.label = QtWidgets.QLabel(parent=self.headerWidget)
        self.label.setGeometry(QtCore.QRect(500, 0, 371, 41))
        self.label.setStyleSheet("  font-size: 30px; /* Cỡ chữ lớn */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    font-family: \"Georgia\", serif; /* Font chữ sang trọng */\n"
"    color: white;\n"
"    text-align: center; ")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.navBar = QtWidgets.QWidget(parent=self.centralwidget)
        self.navBar.setGeometry(QtCore.QRect(0, 40, 1331, 41))
        self.navBar.setStyleSheet("background-color: white;\n"
"border-bottom: 1px solid #ddd;\n"
"")
        self.navBar.setObjectName("navBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.navBar)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 1331, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sortcoffeebeans = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sortcoffeebeans.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.sortcoffeebeans.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 14px;\n"
" font-family: \"Georgia\"\n"
"}\n"
"QPushButton:hover {\n"
"    color: #0D3B66;\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.sortcoffeebeans.setObjectName("sortcoffeebeans")
        self.horizontalLayout.addWidget(self.sortcoffeebeans)
        self.sortcoldbrew = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sortcoldbrew.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.sortcoldbrew.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 14px;\n"
" font-family: \"Georgia\"\n"
"}\n"
"QPushButton:hover {\n"
"    color: #0D3B66;\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.sortcoldbrew.setObjectName("sortcoldbrew")
        self.horizontalLayout.addWidget(self.sortcoldbrew)
        self.sortmatcha = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sortmatcha.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.sortmatcha.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 14px;\n"
" font-family: \"Georgia\"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #0D3B66;\n"
"    text-decoration: underline;\n"
"}")
        self.sortmatcha.setObjectName("sortmatcha")
        self.horizontalLayout.addWidget(self.sortmatcha)
        self.sortchocolate = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sortchocolate.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 14px;\n"
" font-family: \"Georgia\"\n"
"}\n"
"QPushButton:hover {\n"
"    color: #0D3B66;\n"
"    text-decoration: underline;\n"
"}")
        self.sortchocolate.setObjectName("sortchocolate")
        self.horizontalLayout.addWidget(self.sortchocolate)
        self.label_33 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(20, 90, 171, 231))
        self.label_33.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(40, 240, 141, 31))
        self.label_35.setStyleSheet(" font-family: \"Georgia\"")
        self.label_35.setObjectName("label_35")
        self.buychocolatebalance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buychocolatebalance.setGeometry(QtCore.QRect(50, 270, 111, 41))
        self.buychocolatebalance.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/images/3507742_cart_ecommerce_grocery_iconoteka_shop_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buychocolatebalance.setIcon(icon)
        self.buychocolatebalance.setObjectName("buychocolatebalance")
        self.label_37 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(20, 330, 171, 231))
        self.label_37.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_42 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(20, 570, 171, 231))
        self.label_42.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.buydarkchocolate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buydarkchocolate.setGeometry(QtCore.QRect(50, 510, 111, 41))
        self.buydarkchocolate.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buydarkchocolate.setIcon(icon)
        self.buydarkchocolate.setObjectName("buydarkchocolate")
        self.buymilkchocolate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buymilkchocolate.setGeometry(QtCore.QRect(50, 750, 111, 41))
        self.buymilkchocolate.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buymilkchocolate.setIcon(icon)
        self.buymilkchocolate.setObjectName("buymilkchocolate")
        self.imagechocolate_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagechocolate_2.setGeometry(QtCore.QRect(60, 340, 91, 141))
        self.imagechocolate_2.setText("")
        self.imagechocolate_2.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/dark choco 1.png"))
        self.imagechocolate_2.setScaledContents(True)
        self.imagechocolate_2.setObjectName("imagechocolate_2")
        self.label_44 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(30, 480, 171, 31))
        self.label_44.setStyleSheet(" font-family: \"Georgia\"")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(200, 90, 171, 231))
        self.label_45.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.imagechocolate_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagechocolate_3.setGeometry(QtCore.QRect(60, 580, 91, 141))
        self.imagechocolate_3.setText("")
        self.imagechocolate_3.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/milk choco 2.png"))
        self.imagechocolate_3.setScaledContents(True)
        self.imagechocolate_3.setObjectName("imagechocolate_3")
        self.label_47 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(50, 720, 131, 31))
        self.label_47.setStyleSheet(" font-family: \"Georgia\"")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(200, 330, 171, 231))
        self.label_48.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(200, 570, 171, 231))
        self.label_49.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.imagecoffee = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee.setGeometry(QtCore.QRect(240, 580, 91, 131))
        self.imagecoffee.setText("")
        self.imagecoffee.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/Limited.png"))
        self.imagecoffee.setScaledContents(True)
        self.imagecoffee.setObjectName("imagecoffee")
        self.label_51 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(210, 720, 171, 31))
        self.label_51.setStyleSheet(" font-family: \"Georgia\"")
        self.label_51.setObjectName("label_51")
        self.buyclassicalroast = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buyclassicalroast.setGeometry(QtCore.QRect(230, 270, 111, 41))
        self.buyclassicalroast.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buyclassicalroast.setIcon(icon)
        self.buyclassicalroast.setObjectName("buyclassicalroast")
        self.imagecoldbrew = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoldbrew.setGeometry(QtCore.QRect(230, 350, 111, 131))
        self.imagecoldbrew.setText("")
        self.imagecoldbrew.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/Vanila cold breww.png"))
        self.imagecoldbrew.setScaledContents(True)
        self.imagecoldbrew.setObjectName("imagecoldbrew")
        self.label_53 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(220, 480, 161, 31))
        self.label_53.setStyleSheet(" font-family: \"Georgia\"")
        self.label_53.setObjectName("label_53")
        self.buyvanillacoldbrew = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buyvanillacoldbrew.setGeometry(QtCore.QRect(230, 510, 111, 41))
        self.buyvanillacoldbrew.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buyvanillacoldbrew.setIcon(icon)
        self.buyvanillacoldbrew.setObjectName("buyvanillacoldbrew")
        self.imagecoldbrew_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoldbrew_2.setGeometry(QtCore.QRect(230, 120, 111, 121))
        self.imagecoldbrew_2.setStyleSheet("")
        self.imagecoldbrew_2.setText("")
        self.imagecoldbrew_2.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/Classical Cold brew.png"))
        self.imagecoldbrew_2.setScaledContents(True)
        self.imagecoldbrew_2.setObjectName("imagecoldbrew_2")
        self.label_54 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(210, 240, 161, 31))
        self.label_54.setStyleSheet(" font-family: \"Georgia\"")
        self.label_54.setObjectName("label_54")
        self.buymediumroast = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buymediumroast.setGeometry(QtCore.QRect(230, 750, 111, 41))
        self.buymediumroast.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buymediumroast.setIcon(icon)
        self.buymediumroast.setObjectName("buymediumroast")
        self.label_55 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(380, 90, 171, 231))
        self.label_55.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(560, 90, 171, 231))
        self.label_56.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(740, 90, 171, 231))
        self.label_57.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(380, 330, 171, 231))
        self.label_58.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(560, 330, 171, 231))
        self.label_59.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(740, 330, 171, 231))
        self.label_60.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(380, 570, 171, 231))
        self.label_61.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_61.setText("")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(560, 570, 171, 231))
        self.label_62.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_62.setText("")
        self.label_62.setObjectName("label_62")
        self.imagecoffee_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee_2.setGeometry(QtCore.QRect(420, 110, 91, 131))
        self.imagecoffee_2.setText("")
        self.imagecoffee_2.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/original 1.png"))
        self.imagecoffee_2.setScaledContents(True)
        self.imagecoffee_2.setObjectName("imagecoffee_2")
        self.buyvanillaroast = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buyvanillaroast.setGeometry(QtCore.QRect(410, 270, 111, 41))
        self.buyvanillaroast.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buyvanillaroast.setIcon(icon)
        self.buyvanillaroast.setObjectName("buyvanillaroast")
        self.label_41 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(410, 240, 121, 31))
        self.label_41.setStyleSheet(" font-family: \"Georgia\"")
        self.label_41.setObjectName("label_41")
        self.imagematcha = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagematcha.setGeometry(QtCore.QRect(410, 350, 111, 131))
        self.imagematcha.setText("")
        self.imagematcha.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/Matcha.png"))
        self.imagematcha.setScaledContents(True)
        self.imagematcha.setObjectName("imagematcha")
        self.label_36 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(420, 480, 111, 31))
        self.label_36.setStyleSheet(" font-family: \"Georgia\"")
        self.label_36.setObjectName("label_36")
        self.buyujimatcha = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buyujimatcha.setGeometry(QtCore.QRect(410, 510, 111, 41))
        self.buyujimatcha.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buyujimatcha.setIcon(icon)
        self.buyujimatcha.setObjectName("buyujimatcha")
        self.imagematcha_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagematcha_2.setGeometry(QtCore.QRect(410, 590, 111, 131))
        self.imagematcha_2.setText("")
        self.imagematcha_2.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/matcha 2.png"))
        self.imagematcha_2.setScaledContents(True)
        self.imagematcha_2.setObjectName("imagematcha_2")
        self.label_39 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(410, 720, 121, 31))
        self.label_39.setStyleSheet(" font-family: \"Georgia\"")
        self.label_39.setObjectName("label_39")
        self.buykyotomatcha = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buykyotomatcha.setGeometry(QtCore.QRect(410, 750, 111, 41))
        self.buykyotomatcha.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; \n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; \n"
"    border: 2px solid #3E2723; /\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; \n"
"    border: 2px solid #6D4C41; \n"
"}\n"
"")
        self.buykyotomatcha.setIcon(icon)
        self.buykyotomatcha.setObjectName("buykyotomatcha")
        self.imagechocolate = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagechocolate.setGeometry(QtCore.QRect(60, 100, 91, 141))
        self.imagechocolate.setText("")
        self.imagechocolate.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/belgian choco.png"))
        self.imagechocolate.setScaledContents(True)
        self.imagechocolate.setObjectName("imagechocolate")
        self.imagecoffee_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee_3.setGeometry(QtCore.QRect(600, 110, 91, 131))
        self.imagecoffee_3.setText("")
        self.imagecoffee_3.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/med roát.png"))
        self.imagecoffee_3.setScaledContents(True)
        self.imagecoffee_3.setObjectName("imagecoffee_3")
        self.label_65 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(590, 240, 161, 31))
        self.label_65.setStyleSheet(" font-family: \"Georgia\"")
        self.label_65.setObjectName("label_65")
        self.buyspecialblend = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buyspecialblend.setGeometry(QtCore.QRect(590, 270, 111, 41))
        self.buyspecialblend.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buyspecialblend.setIcon(icon)
        self.buyspecialblend.setObjectName("buyspecialblend")
        self.buydarkroast = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buydarkroast.setGeometry(QtCore.QRect(590, 510, 111, 41))
        self.buydarkroast.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buydarkroast.setIcon(icon)
        self.buydarkroast.setObjectName("buydarkroast")
        self.buylightroast = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buylightroast.setGeometry(QtCore.QRect(590, 750, 111, 41))
        self.buylightroast.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buylightroast.setIcon(icon)
        self.buylightroast.setObjectName("buylightroast")
        self.buymochacoffee = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buymochacoffee.setGeometry(QtCore.QRect(770, 510, 111, 41))
        self.buymochacoffee.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buymochacoffee.setIcon(icon)
        self.buymochacoffee.setObjectName("buymochacoffee")
        self.imagecoffee_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee_5.setGeometry(QtCore.QRect(600, 340, 91, 141))
        self.imagecoffee_5.setText("")
        self.imagecoffee_5.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/espresso.png"))
        self.imagecoffee_5.setScaledContents(True)
        self.imagecoffee_5.setObjectName("imagecoffee_5")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 490, 111, 16))
        self.label_4.setStyleSheet(" font-family: \"Georgia\"")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 730, 111, 16))
        self.label_6.setStyleSheet(" font-family: \"Georgia\"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(770, 250, 131, 20))
        self.label_7.setStyleSheet(" font-family: \"Georgia\"\n"
"")
        self.label_7.setObjectName("label_7")
        self.buyinstantcoffee = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buyinstantcoffee.setGeometry(QtCore.QRect(770, 270, 111, 41))
        self.buyinstantcoffee.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        self.buyinstantcoffee.setIcon(icon)
        self.buyinstantcoffee.setObjectName("buyinstantcoffee")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(770, 490, 131, 20))
        self.label_8.setStyleSheet(" font-family: \"Georgia\"\n"
"")
        self.label_8.setObjectName("label_8")
        self.imagecoffee_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee_7.setGeometry(QtCore.QRect(600, 580, 91, 141))
        self.imagecoffee_7.setText("")
        self.imagecoffee_7.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/tokyo roast.png"))
        self.imagecoffee_7.setScaledContents(True)
        self.imagecoffee_7.setObjectName("imagecoffee_7")
        self.imagecoffee_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee_4.setGeometry(QtCore.QRect(770, 110, 111, 131))
        self.imagecoffee_4.setText("")
        self.imagecoffee_4.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/Không có tiêu đề.png"))
        self.imagecoffee_4.setScaledContents(True)
        self.imagecoffee_4.setObjectName("imagecoffee_4")
        self.imagecoffee_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagecoffee_6.setGeometry(QtCore.QRect(780, 340, 91, 141))
        self.imagecoffee_6.setText("")
        self.imagecoffee_6.setPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/mocha.png"))
        self.imagecoffee_6.setScaledContents(True)
        self.imagecoffee_6.setObjectName("imagecoffee_6")
        self.pushButton_TB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_TB.setGeometry(QtCore.QRect(1120, 750, 201, 41))
        self.pushButton_TB.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_TB.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/2987779_coffee_cup_drink_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_TB.setIcon(icon1)
        self.pushButton_TB.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_TB.setObjectName("pushButton_TB")
        self.pushButtonPM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPM.setGeometry(QtCore.QRect(910, 700, 201, 41))
        self.pushButtonPM.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButtonPM.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/2921798_business_corporate_development_management_marketing_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPM.setIcon(icon2)
        self.pushButtonPM.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonPM.setObjectName("pushButtonPM")
        self.reload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reload.setGeometry(QtCore.QRect(910, 750, 201, 41))
        self.reload.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.reload.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/59300_refresh_reload_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reload.setIcon(icon3)
        self.reload.setObjectName("reload")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1015, 130, 60, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(930, 130, 391, 561))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(202, 161, 151);\n"
"    font-family: \"Georgia\";size: 14;\n"
"    gridline-color: #dcdcdc; /* Màu đường kẻ */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    text-align: center; /* Căn chữ giữa */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f2f2f2\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(970, 630, 331, 51))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 100); /* Màu trắng, trong suốt 40% */\n"
"    border-radius: 20px;  /* Bo góc 15px */\n"
"    padding: 5px; /* Tạo khoảng cách giữa nội dung và viền */\n"
"    font-size: 14px;\n"
"    font-family: Georgia;\n"
"    color: black; /* Màu chữ */\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(990, 650, 60, 16))
        self.label_9.setStyleSheet(" font-family: \"Georgia\"\n"
"")
        self.label_9.setObjectName("label_9")
        self.labelTB = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTB.setGeometry(QtCore.QRect(1120, 640, 171, 31))
        self.labelTB.setText("")
        self.labelTB.setObjectName("labelTB")
        self.staffname = QtWidgets.QLabel(parent=self.centralwidget)
        self.staffname.setGeometry(QtCore.QRect(1020, 90, 201, 31))
        self.staffname.setStyleSheet("background-color: rgb(239, 147, 130);\n"
"")
        self.staffname.setText("")
        self.staffname.setObjectName("staffname")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(950, 540, 161, 51))
        self.label_2.setStyleSheet(" font-family: \"Georgia\"\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit_PhoneNum = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_PhoneNum.setGeometry(QtCore.QRect(1130, 550, 141, 31))
        self.lineEdit_PhoneNum.setText("")
        self.lineEdit_PhoneNum.setObjectName("lineEdit_PhoneNum")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(950, 570, 161, 51))
        self.label_11.setStyleSheet(" font-family: \"Georgia\"\n"
"")
        self.label_11.setObjectName("label_11")
        self.lineEdit_CustomerType = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_CustomerType.setGeometry(QtCore.QRect(1130, 590, 141, 31))
        self.lineEdit_CustomerType.setObjectName("lineEdit_CustomerType")
        self.pushButton_loadCusType = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_loadCusType.setGeometry(QtCore.QRect(1280, 550, 31, 31))
        self.pushButton_loadCusType.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/7479650_literature_literature review_search_find_read_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_loadCusType.setIcon(icon4)
        self.pushButton_loadCusType.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_loadCusType.setObjectName("pushButton_loadCusType")
        self.pushButtonNextBill = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonNextBill.setGeometry(QtCore.QRect(1120, 700, 201, 41))
        self.pushButtonNextBill.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButtonNextBill.setStyleSheet("QPushButton {\n"
"    background-color: #8B5E3C; /* Màu nâu cà phê đậm */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4E342E; /* Viền nâu trầm */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6D4C41; /* Màu nâu đất đậm hơn khi hover */\n"
"    border: 2px solid #3E2723; /* Viền nâu đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A1887F; /* Màu be nâu sáng khi nhấn */\n"
"    border: 2px solid #6D4C41; /* Viền nâu trung tính */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/dovi/ProductManagement/Final/ui/../images/7007504_payment_bill_invoice_receipt_business_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNextBill.setIcon(icon5)
        self.pushButtonNextBill.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonNextBill.setObjectName("pushButtonNextBill")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1344, 24))
        self.menubar.setObjectName("menubar")
        self.menuHOME = QtWidgets.QMenu(parent=self.menubar)
        self.menuHOME.setObjectName("menuHOME")
        self.menuProduct_Management = QtWidgets.QMenu(parent=self.menubar)
        self.menuProduct_Management.setObjectName("menuProduct_Management")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_us = QtGui.QAction(parent=MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.actionCoffee = QtGui.QAction(parent=MainWindow)
        self.actionCoffee.setObjectName("actionCoffee")
        self.actionAbout_us_2 = QtGui.QAction(parent=MainWindow)
        self.actionAbout_us_2.setObjectName("actionAbout_us_2")
        self.actionLogin_ProductMangement = QtGui.QAction(parent=MainWindow)
        self.actionLogin_ProductMangement.setObjectName("actionLogin_ProductMangement")
        self.actionCold_Brew = QtGui.QAction(parent=MainWindow)
        self.actionCold_Brew.setObjectName("actionCold_Brew")
        self.actionChocolate = QtGui.QAction(parent=MainWindow)
        self.actionChocolate.setObjectName("actionChocolate")
        self.actionAbout_us_3 = QtGui.QAction(parent=MainWindow)
        self.actionAbout_us_3.setObjectName("actionAbout_us_3")
        self.menuHOME.addAction(self.actionCoffee)
        self.menuHOME.addSeparator()
        self.menuHOME.addAction(self.actionAbout_us_2)
        self.menuHOME.addSeparator()
        self.menuHOME.addAction(self.actionCold_Brew)
        self.menuHOME.addSeparator()
        self.menuHOME.addAction(self.actionChocolate)
        self.menuHOME.addSeparator()
        self.menuHOME.addAction(self.actionAbout_us_3)
        self.menuHOME.addSeparator()
        self.menuProduct_Management.addAction(self.actionLogin_ProductMangement)
        self.menubar.addAction(self.menuHOME.menuAction())
        self.menubar.addAction(self.menuProduct_Management.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MY COFFEE SHOP"))
        self.sortcoffeebeans.setText(_translate("MainWindow", "Coffee beans"))
        self.sortcoldbrew.setText(_translate("MainWindow", "Cold brew"))
        self.sortmatcha.setText(_translate("MainWindow", "Matcha"))
        self.sortchocolate.setText(_translate("MainWindow", "Chocolate"))
        self.label_35.setText(_translate("MainWindow", "Chocolate Balance - 36$"))
        self.buychocolatebalance.setText(_translate("MainWindow", "Add to cart"))
        self.buydarkchocolate.setText(_translate("MainWindow", "Add to cart"))
        self.buymilkchocolate.setText(_translate("MainWindow", "Add to cart"))
        self.label_44.setText(_translate("MainWindow", "Dark Chocolate (65%)- 50$"))
        self.label_47.setText(_translate("MainWindow", "Milk Chocolate - 55$"))
        self.label_51.setText(_translate("MainWindow", "Medium Roast Blend - 45$ "))
        self.buyclassicalroast.setText(_translate("MainWindow", "Add to cart"))
        self.label_53.setText(_translate("MainWindow", "Vanilla Cold Brew - 40$"))
        self.buyvanillacoldbrew.setText(_translate("MainWindow", "Add to cart"))
        self.label_54.setText(_translate("MainWindow", "Classical Cold Brew - 38$"))
        self.buymediumroast.setText(_translate("MainWindow", "Add to cart"))
        self.buyvanillaroast.setText(_translate("MainWindow", "Add to cart"))
        self.label_41.setText(_translate("MainWindow", "Vanilla Roast - 40$"))
        self.label_36.setText(_translate("MainWindow", "Uji Matcha - 70$"))
        self.buyujimatcha.setText(_translate("MainWindow", "Add to cart"))
        self.label_39.setText(_translate("MainWindow", "Kyoto Matcha - 80$"))
        self.buykyotomatcha.setText(_translate("MainWindow", "Add to cart"))
        self.label_65.setText(_translate("MainWindow", "Special Blend - 35$"))
        self.buyspecialblend.setText(_translate("MainWindow", "Add to cart"))
        self.buydarkroast.setText(_translate("MainWindow", "Add to cart"))
        self.buylightroast.setText(_translate("MainWindow", "Add to cart"))
        self.buymochacoffee.setText(_translate("MainWindow", "Add to cart"))
        self.label_4.setText(_translate("MainWindow", "Dark Roast - 45$"))
        self.label_6.setText(_translate("MainWindow", " Light Roast - 35$"))
        self.label_7.setText(_translate("MainWindow", "Instant Coffee - 30$"))
        self.buyinstantcoffee.setText(_translate("MainWindow", "Add to cart"))
        self.label_8.setText(_translate("MainWindow", "Mocha Coffee - 30$"))
        self.pushButton_TB.setText(_translate("MainWindow", "Total Bill"))
        self.pushButtonPM.setText(_translate("MainWindow", "Product Management"))
        self.reload.setText(_translate("MainWindow", "Reload Menu"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Items"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        self.label_9.setText(_translate("MainWindow", "Total Bill: "))
        self.label_2.setText(_translate("MainWindow", "Customer\'s Phone Number:"))
        self.label_11.setText(_translate("MainWindow", "Customer\'s Type: "))
        self.pushButtonNextBill.setText(_translate("MainWindow", "Next Bill"))
        self.menuHOME.setTitle(_translate("MainWindow", "HOME"))
        self.menuProduct_Management.setTitle(_translate("MainWindow", "Product Management"))
        self.actionAbout_us.setText(_translate("MainWindow", "About us"))
        self.actionCoffee.setText(_translate("MainWindow", "Coffee"))
        self.actionAbout_us_2.setText(_translate("MainWindow", "Matcha"))
        self.actionLogin_ProductMangement.setText(_translate("MainWindow", "Login ProductMangement"))
        self.actionCold_Brew.setText(_translate("MainWindow", "Cold Brew"))
        self.actionChocolate.setText(_translate("MainWindow", "Chocolate"))
        self.actionAbout_us_3.setText(_translate("MainWindow", "About us"))
